#' Cross Tabulate Summary Counts
#'
#' Create a contingency table of counts generated by cross-classifying
#' factors from groups splitting on the `by` argument,
#' and an optional secondary splitting variable. The sums of each
#' row and column are added to the result.
#'
#' @aliases crossTab my.table
#' @param x A "data.frame" or "tibble" object containing the
#' data from which counts are desired.
#' @param by Character. The grouping variable(s). Can be of
#' `length=1` or `length = 2`, if `length = 2` a 2-dim
#' table will be returned.
#' @return A table of grouped counts based on splitting variables with sums
#' from each factor.
#' @note This is a simple wrapper around \code{\link{table}}
#' that adds the sums of columns and rows to the final object
#' @author Stu Field
#' @seealso \code{\link{table}}, \code{\link[stats]{addmargins}}
#' @examples
#' crossTab(test_data, by = "Sample")
#' crossTab(test_data, by = c("Sample", "TimePoint"))
#' @importFrom stats addmargins
#' @export crossTab
crossTab <- function(x, by) {
  if ( !all(by %in% names(x)) ) {
    stop("Missing or misspelled entry in [by=] argument: ",
         paste(by, collapse = ", "), call. = FALSE)
  }
  x[, by] %>% table() %>% stats::addmargins()
}
